// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using brainfreeze_new.Server.Models;

#nullable disable

namespace brainfreeze_new.Server.Migrations
{
    [DbContext(typeof(ScoreboardDBContext))]
    [Migration("20241111145223_initCreate")]
    partial class initCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("brainfreeze_new.Server.Models.Scoreboard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cardflipScore")
                        .HasColumnType("int");

                    b.Property<int>("nrgScore")
                        .HasColumnType("int");

                    b.Property<int>("place")
                        .HasColumnType("int");

                    b.Property<int>("simonScore")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("scoreboards");
                });
#pragma warning restore 612, 618
        }
    }
}
