@brainfreeze_new.Server_HostAddress = http://localhost:5219

### GET Request
GET {{brainfreeze_new.Server_HostAddress}}/api/Inc
Accept: application/json

### POST Request
POST {{brainfreeze_new.Server_HostAddress}}/api/Inc
Accept: application/json
